config/routes.rb
Rails.application.routes.draw do
  resources :uploads, only: [:index, :create, :destroy] do
    get :share, on: :member
  end
  get "uploads/:id/:file_name" => "uploads#download", as: :download_uploaded_file
  get "files/:id" => "uploads#download", as: :public_download

  resources :sessions, only: [:create]
  resources :users, only: [:new, :create]

  get '/login' => 'sessions#new'
  delete '/logout' => 'sessions#destroy'


  root to: 'uploads#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/upload.rb
class Upload < ApplicationRecord
  BLACKLISTED_EXTENSIONS = ["js"]

  attr_accessor :uploaded_file

  has_secure_token :access_token

  belongs_to :user

  validates :file, :content_type, presence: true
  validates :access_token, presence: true, uniqueness: true, on: :update

  validate do
    self.errors.add(:file, "upload must be present.") unless uploaded_file.present?
  end

  after_save :persist_file
  after_destroy :remove_file

  def file_url
    '/' + storage_url + '/' + file
  end

  def file_path
    storage_path + file
  end

  def storage_path
    Rails.root.join(storage_url)
  end

  def file?
    file.presence && File.exist?(file_path)
  end

  def exported_name
    extn = File.extname(file)
    extn.slice!(0)
    BLACKLISTED_EXTENSIONS.include?(extn) ? "#{file}.txt" : file
  end

  private

  def storage_url
    "uploads/#{self.class.to_s.underscore}/file/#{self.id}"
  end

  def persist_file
    FileUtils.mkdir_p(storage_path) unless Dir.exist?(storage_path)
    File.open(file_path, 'wb') {|f| f.write(uploaded_file.read) }
  end

  def remove_file
    File.delete(file_path) if File.exist?(file_path)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true, email: true
  validates :password, confirmation: true, length: {minimum: 6}, on: :create
  validates :password_confirmation, presence: true, if: 'password.present?'

  has_many :uploads, dependent: :destroy

  before_validation do
    self.email&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  before_action :authenticate

  private

  rescue_from ActionController::InvalidAuthenticityToken do |exception|
    session.clear
    flash[:error] = "You are not logged in."
    redirect_to login_path
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate
      redirect_to '/login' unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]

  def new
    redirect_to root_path and return if current_user.present?
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:notice] = "Signed in successfully."
      redirect_to root_path
    else
      flash[:error] = "Incorrect email/password."
      render :new
    end
  end

  def destroy
    if current_user
      session.clear
      flash[:notice] = "Signed out successfully."
    else
      flash[:error] = "You are not authorized to view this page."
    end
    redirect_to login_path
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :get_upload, only: [:destroy, :download, :share]

  def index
    @uploads = current_user.uploads
  end

  def create
    uploaded_file = params[:upload].presence && params[:upload][:file]
    redirect_to uploads_path, alert: 'Unable to upload file.' and return unless uploaded_file.present?

    @upload = Upload.new.tap do |u|
      u.user = current_user
      u.file = uploaded_file.original_filename
      u.content_type = uploaded_file.content_type
      u.uploaded_file = uploaded_file
    end

    if @upload.save
      flash[:notice] = 'File was successfully uploaded.'
    else
      flash[:error] = 'Unable to upload file.'
    end
    redirect_to uploads_path
  end

  def destroy
    unless @upload.present?
      flash[:error] = "File not found."
      redirect_to uploads_url and return
    end

    if @upload.destroy
      flash[:notice] = 'File was successfully deleted.'
    else
      flash[:error] = 'Unable to delete file.'
    end
      redirect_to uploads_url
  end

  def download
    if @upload.present? && @upload.file?
      send_file @upload.file_path, filename: @upload.exported_name, type: @upload.content_type, disposition: :attachment
    else
      flash[:error] = "File not found."
      redirect_to uploads_url
    end
  end

  def share
    head :not_found and return unless @upload.present?
  end

  private

  def get_upload
    uploads = Upload.where(user_id: current_user.id)
    @upload = if params[:action] == 'download'
                uploads.where(access_token: params[:id]).first
              else
                uploads.where(id: params[:id]).first
              end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]

  def new
    redirect_to root_path and return if current_user.present?
    @user = User.new
  end

  def create
    @user = User.new(create_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Sign up successful."
      redirect_to root_path
    else
      flash[:error] = "Unable to sign up. Please correct the errors."
      render :new
    end
  end

  private

  def create_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.haml
.navbar.navbar-default
  .container-fluid
    .navbar-header
      = link_to "Rapidshare", "#", class: "navbar-brand"
    - if current_user
      .collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to "Logout", logout_path, method: :delete, data: {confirm: "Are you sure you want to log out?"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RapidshareClone
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    - flash.each do |key, value|
      - type = key == 'notice' ? 'success' : ((key == 'error' || key == 'alert') ? 'danger' : key)
      %div{id: 'flash', class: "text-center alert alert-#{type}"}
        = value
    - flash.clear

    = render 'header' if params[:controller] != 'sessions' && params[:controller] != 'users'
    .container
      = yield

:coffeescript
  $(document).ready ->
    window.setTimeout (->
      $('#flash').fadeOut()
    ), 5000

app/views/uploads/_share.html.haml
.modal-dialog{:role => "document"}
  .modal-content
    .modal-header
      %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
        %span{"aria-hidden" => "true"} ×
      %h4.modal-title Public Url
    .modal-body
      %p
        Your public url for #{upload.filename} is
        %br
        = "#{request.base_url}/files/#{upload.access_token}"
    .modal-footer
      %button.btn.btn-default{data: {dismiss: "modal"}, type: "button"} Close

app/views/uploads/_upload.html.haml
.file-upload.col-xs-6.col-md-2
  .thumbnail
    .file-name
      = upload.file
    .hr-separator
    .file-placeholder
      - if upload.content_type&.include?('image')
        = image_tag download_uploaded_file_path(upload.access_token, upload.file)
      - else
        = image_tag 'placeholder.png'
    .hr-separator
    .row.text-center
      = link_to share_upload_path(upload), class: 'btn btn-info', remote: true do
        %i.glyphicon.glyphicon-share
      = link_to download_uploaded_file_path(upload.access_token, upload.file), class: 'btn btn-primary' do
        %i.glyphicon.glyphicon-download-alt
      = link_to upload, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
        %i.glyphicon.glyphicon-remove

app/views/uploads/index.html.haml
.row.text-centered
  = form_for Upload.new, class: 'form-inline' do |f|
    = f.file_field :file, class: 'hide'
    .col-lg-8.col-lg-offset-2
      .form-group
        .input-group
          = text_field_tag "file_name", nil,  class: 'form-control', placeholder: 'Choose file to upload...', disabled: true
          .input-group-btn
            = button_tag 'Choose', type: 'button', id: 'choose-file-btn', class: 'btn btn-default'
            = f.submit 'Upload', id: 'upload-file-btn', class: 'btn btn-primary', disabled: true

%h3.text-center My files

- @uploads.each_slice(6) do |upload_group|
  .row
    - upload_group.each do |upload|
      = render 'upload', upload: upload


#share-modal.modal.fade.hide{:role => "dialog", :tabindex => "-1"}

app/views/uploads/share.js.haml
$("#share-modal").html("#{escape_javascript(render 'share', upload: @upload)}");
$("#share-modal").removeClass('hide');
$("#share-modal").modal('show');

app/views/users/new.html.haml
.center-box.signup
  %h3.text-center Sign Up

  = form_for @user, html: {class: 'form'} do |f|
    .form-group{class: (@user.errors[:name].presence && 'has-error')}
      = f.label :name
      = f.text_field :name, class: 'form-control'
      - if @user.errors[:name].present?
        %span{id: "help-block-name", class: "help-block"}
          = @user.errors.full_messages_for(:name).join(', ')

    .form-group{class: (@user.errors[:email].presence && 'has-error')}
      = f.label :email
      = f.email_field :email, class: 'form-control'
      - if @user.errors[:email].present?
        %span{id: "help-block-email", class: "help-block"}
          = @user.errors.full_messages_for(:email).join(', ')

    .form-group{class: (@user.errors[:password].presence && 'has-error')}
      = f.label :password
      = f.password_field :password, class: 'form-control'
      - if @user.errors[:password].present?
        %span{id: "help-block-password", class: "help-block"}
          = @user.errors.full_messages_for(:password).join(', ')

    .form-group{class: (@user.errors[:password_confirmation].presence && 'has-error')}
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: 'form-control'
      - if @user.errors[:password_confirmation].present?
        %span{id: "help-block-password-confirmation", class: "help-block"}
          = @user.errors.full_messages_for(:password_confirmation).join(', ')

    .text-center
      = link_to "Sign In", login_path, class: 'btn btn-primary'
      = f.submit "Sign Up", class: 'btn btn-success'